name: "🐛 Bug Report"
description: "Something isn't working"
labels: ["bug"]
body:
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows 10
        - Windows 11
        - macOS
        - Linux
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js version
      placeholder: "e.g. 20.11.0"

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior

  - type: textarea
    id: logs
    attributes:
      label: Error logs
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
