name: "✨ Feature Request"
description: "Suggest an improvement"
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem description
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Detection
        - File Monitoring
        - Network
        - UI/Dashboard
        - Risk Scoring
        - Agent Database
        - Other
